### ISSUE TITLE
Implement new outline function that generates structure like LSP likes

### ISSUE THREAD

**Issue by DavyLandman** [cwi-swat/rascal-vscode#13]

**Comment by jurgenvinju** [comment]
this is done for the parametric LSP; we can port it easily when the Rascal LSP support switches to the newer interfaces.

**Comment by DavyLandman** [comment]
I want to leave it open, since we need to do this for rascal. That why this issue is here.

**Comment by jurgenvinju** [comment]
we could write and use  a `lang::rascal::lsp::Outline` module in the rascal-lsp library and call that instead of the `lang::rascal::ide::Outline` module.

**Comment by jurgenvinju** [comment]
I'll start on that.

**Comment by DavyLandman** [comment]
finished integrating it
