### ISSUE TITLE
Removing all declarations and uses of annotations from the standard library

### ISSUE THREAD

**Issue by jurgenvinju** [cwi-swat/rascal-vscode#50]
* We've tested and released Rascal versions which simulate the behavior of annotation declarations and uses via the keyword field feature.
* This works well. The standard library being the biggest user of this feature (like ParseTree.rsc) 
* We can now start removing all the declarations and uses of annotation syntax and replacing it by keyword field syntax with the same semantics
* There is already a refactoring script which can do this automatically (lang::rascal::refactoring::upgrade) on one of the annotation branches. This could be revived.
* After this refactoring the standard library will be rid of all the deprecation warnings by the type-checker and be a better model of how to write typical Rascal code again.

**Comment by DavyLandman** [comment]
Does this belong on this repo? I did do it in a branch already, for the outline code...

**Comment by jurgenvinju** [comment]
Nope. wrong repo!
